[workspace]

members = [
    "nes-core",
    "nes-frontend",
    "run-wasm"
]

resolver = "2" # needed due to bug in wgpu

[profile.release-small]
inherits = "release"
strip = "symbols"
lto = true
opt-level = "s"
