[package]
name = "nes-frontend"
version = "0.1.0"
edition = "2021"
default-run = "nes"

[dependencies]
nes-core = { path = "../nes-core" }
log = "0.4"
pixels = "0.17"
winit = "0.30"
winit_input_helper = "0.17"
web-time = "1.1"
fnv = "1.0"
egui = "0.35"
egui-wgpu = "0.35"
egui-winit = { version = "0.35", default-features = false, features = ["links"] }
game-loop = { version = "1.3", features = ["winit"] }
include_dir = "0.7"
rfd = "0.17"
tokio = { version = "1.53", features = ["sync"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "1.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["GpuTextureFormat"] }
# wasm-timer = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"
pollster = "1.0"
spin_sleep = "1.3"

[[bin]]
name = "nes"
